version: '3.8'

services:
  bird-bot:
    image: bird-bot
    container_name: bird-bot
    build:
      context: .
    env_file:
      - .env
    restart: unless-stopped

  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    volumes:
      - ./data:/data/db